name:                icfpc-y2024
version:             0.1.0.0
github:              "githubuser/icfpc-y2024"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/icfpc-y2024#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- text >= 2.0.2
- containers >= 0.6
- http-conduit
- megaparsec >= 9.5.0
- pretty-simple

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -XOverloadedStrings

default-extensions:
- OverloadedStrings

library:
  source-dirs: src
  dependencies:
    - containers
    - text

executables:
  icfpc-y2024-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - icfpc-y2024
    - text

tests:
  icfpc-y2024-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - icfpc-y2024
    - tasty
    - tasty-hunit
    - tasty-quickcheck
