EXE = ./solver.exe

all:
	g++ -fsanitize=address -O3 -g solve_lambdaman.cpp -std=c++17 -o $(EXE)
	$(EXE) lambdaman1.txt > lambdaman1.sol || true
	$(EXE) lambdaman2.txt > lambdaman2.sol || true
	$(EXE) lambdaman3.txt > lambdaman3.sol || true
	$(EXE) lambdaman4.txt > lambdaman4.sol || true
	$(EXE) lambdaman5.txt > lambdaman5.sol || true
	$(EXE) lambdaman6.txt > lambdaman6.sol || true
	$(EXE) lambdaman7.txt > lambdaman7.sol || true
	$(EXE) lambdaman8.txt > lambdaman8.sol || true
	$(EXE) lambdaman9.txt > lambdaman9.sol || true
	$(EXE) lambdaman10.txt > lambdaman10.sol || true
	$(EXE) lambdaman11.txt > lambdaman11.sol || true
	$(EXE) lambdaman12.txt > lambdaman12.sol || true
	$(EXE) lambdaman13.txt > lambdaman13.sol || true
	$(EXE) lambdaman14.txt > lambdaman14.sol || true
	$(EXE) lambdaman15.txt > lambdaman15.sol || true
	$(EXE) lambdaman16.txt > lambdaman16.sol || true
	$(EXE) lambdaman17.txt > lambdaman17.sol || true
	$(EXE) lambdaman18.txt > lambdaman18.sol || true
	$(EXE) lambdaman19.txt > lambdaman19.sol || true
	$(EXE) lambdaman20.txt > lambdaman20.sol || true
	$(EXE) lambdaman21.txt > lambdaman21.sol || true
