name: Main
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        image:
          - macos-14
          - ubuntu-24.04
          - windows-2022
      fail-fast: false
    runs-on: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Haskell
        uses: haskell-actions/setup@v2
        with:
          stack-version: '2.5.17'
      - name: Build
        run: stack build
      - name: Test
        run: stack test
        timeout-minutes: 10
